# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Speakeasy' do
pod 'QuickBlox'
end

target 'SpeakeasyTests' do

end

target 'SpeakeasyUITests' do

end

